# <span style="color:#2c061f"> Macro 318: Tutorial #1 </span>  

<br>

## <span style="color:#374045"> Introduction to Programming with Julia </span>


#### <span style="color:#374045"> Lecturer: </span> <span style="color:#d89216"> <br> Dawie van Lill (dvanlill@sun.ac.za) </span>

# Introduction

Your interest in computational work will determine how much of this guide you read. 

- **Very interested** -- Read all the sections carefully (even if you don't understand)
- *Somewhat interested* -- Read through the compulsory sections and scan through the `optional` sections
- No interest -- Read the compulsory sections that are needed to complete the tutorials

Try not to let the amount of information overwhelm you.

The notebook is meant to be used as a **reference**

The slides presented here are the **compulsory** part of the tutorial. 

# Tutorial topics

Here are some of the focus areas

1. **Fundamentals of programming with Julia**
2. Data, math and stats
3. Optimisation and the consumer problem
4. Solow model 

# Running the notebooks

It is preferred that you install the programs on your computer.

This requires that you install Anaconda and Julia. 

[Here](https://julia.quantecon.org/getting_started_julia/getting_started.html) is a link that explains the installation process.

However, if you are finding it difficult to get things working you may try the other options. 

I will make a brief video on how to install Anaconda and link it to Julia.


# Tutorial outline

1. Variables
2. Data structures
3. Control flow
4. Functions
5. Visualisation
6. Type system and generic programming (`optional`)

# Your first code!

Before we start our discussion, let us try and run our first Julia program. 

For those that have done programming before, this normally entails writing a piece of code that gives us the output ``Hello World!``. 

In Julia this is super easy to do. 


In [1]:
println("Hello World!")

Hello World!


# Introduction to packages

Julia has many useful packages. If we want to include a specific package then we can do the following,

`import Pkg`

`Pkg.add("PackageName")`

`using PackageName`

In [2]:
import Pkg

Pkg.add("DataFrames") # Package for working with data
Pkg.add("GLM") # Package for linear regression
Pkg.add("LinearAlgebra") # Package for linear algebra applications
Pkg.add("Plots") # Package for plotting
Pkg.add("TypeTree") # Package that shows type hierarchy in tree form

using Base: show_supertypes
using DataFrames
using GLM
using LinearAlgebra
using Plots
using TypeTree

    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
┌ Warning: The active manifest file at `/home/dawie/Dropbox/2022/318-macro/git/Macro-318/Manifest.toml` has an old format that is being maintained.
│ To update to the new format run `Pkg.upgrade_manifest()` which will upgrade the format without re-resolving.
└ @ Pkg.Types /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/Pkg/src/manifest.jl:287
  No Changes to `~/Dropbox/2022/318-macro/git/Macro-318/Project.toml`
  No Changes to `~/Dropbox/2022/318-macro/git/Macro-318/Manifest.toml`
┌ Warning: The active manifest file is an older format with no julia version entry. Dependencies may have been resolved with a different julia version.
└ @ nothing /home/dawie/Dropbox/2022/318-macro/git/Macro-318/Manifest.toml:0
   Resolving package versions...
  No Changes to `~/Dropbox/2022/318-macro/git/Macro-318/Project.toml`
  No Changes to `~/Dropbox/2022/318-macro/git/Macro-318/Manifest.to

In [ ]:
import Pkg

Pkg.add("DataFrames") # Package for working with data
Pkg.add("GLM") # Package for linear regression
Pkg.add("LinearAlgebra") # Package for linear algebra applications
Pkg.add("Plots") # Package for plotting
Pkg.add("TypeTree") # Package that shows type hierarchy in tree form

using Base: show_supertypes
using DataFrames
using GLM
using LinearAlgebra
using Plots
using TypeTree

# Variables and types

After having successfully written your `Hello World!` code in Julia, a natural place to continue your journey is with variables. 

A variable in a programming language is going to be some sort of symbol that we assign some value. 

In [3]:
x = 2 # We assign the value of 2 to the variable x

2

In [4]:
typeof(x) # Command to find the type of the x variable

Int64

We see that the type of the variable is `Int64`. 

What is an `Int64`? 

# Variables and types

We can now work with `x` as if it represents the value of `2`. 

Since an integer is a number, we can perform basic mathematical operations. 

In [5]:
y = x + 2

4

In [6]:
typeof(y)

Int64

# Variables and types

We can reassign the variable `x` to another value, even with another type. 

In [7]:
x = 3.1345

3.1345

In [8]:
typeof(x)

Float64

Now `x` is a floating point number. 

What is a floating point number? 

This is an *approximation* to a decimal (or real) number. 

# Primitive data types

There are several important data types that are at the core of computing. Some of these include, 

- **Booleans**: true and false
- **Integers**: -3, -2, -1, 0, 1, 2, 3, etc.
- **Floating point numbers**: 3.14, 2.95, 1.0, etc.
- **Strings**: "abc", "cat", "hello there"
- **Characters**: 'f', 'c', 'u'

# Arithmetic operators

We can perform basic arithmetic operations. 

Operators perform operations. 

These common operators are called the **arithmetic operators**. 

| Expression | Name           | Description                              |
| :--        | :--            | :--                                      |
| `x + y`    | binary plus    | performs addition                        |
| `x - y`    | binary minus   | performs subtraction                     |
| `x * y`    | times          | performs multiplication                  |
| `x / y`    | divide         | performs division                        |
| `x ÷ y`    | integer divide | `x / y`, truncated to an integer         |
| `x \ y`    | inverse divide | equivalent to `y / x`                    |
| `x ^ y`    | power          | raises `x` to the `y`th power            |
| `x % y`    | remainder      | equivalent to `rem(x,y)`                 |

# Arithmetic operators

Here are some simple examples that utilise these arithmetic operators. 

In [9]:
x = 2; y = 10;

In [10]:
x * y

20

In [11]:
x ^ y

1024

In [12]:
y / x # Note that division converts integers to floats

5.0

In [13]:
2x - 3y

-26

In [14]:
x // y

1//5

# Augmentation operators

Augmentation operators will be especially important in the section on control flow.

In [15]:
x += 1 # same as x = x + 1

3

In [16]:
x *= 2 # same as x = x * 2

6

In [17]:
x /= 2 # same as x = x / 2 

3.0

# Comparison operators

These operators help to generate true and false values for our conditional statements

| Operator  | Name                     |
| :--       | :--                      |
| `==`      | equality                 |
| `!=`, `≠` | inequality               |
| `<`       | less than                |
| `<=`, `≤` | less than or equal to    |
| `>`       | greater than             |
| `>=`, `≥` | greater than or equal to |


In [18]:
x = 3; y = 2; 

In [19]:
x < y # If x is less than y this will return true, otherwise false

false

In [20]:
x != y # If x is not equal to y then this will return true, otherwise false

true

In [21]:
x == y # If x is equal to y this will return true, otherwise false

false

# Data Structures

There are several types of containers, such as arrays and tuples, in Julia. 

These containers contain data of different types. 

We explore some of the most commonly used containers here. 

Note that we have both **mutable** and **immutable** containers in Julia.

# Tuples

Let us start with one of the basic types of containers, which are referred to as tuples. 

These containers are immutable, ordered and of a fixed length. 

In [22]:
x = (10, 20, 30)

(10, 20, 30)

In [23]:
x[1] # First element of the tuple

10

In [24]:
a, b, c = x # With this method of unpacking we have that a = 10, b = 20, c = 30

(10, 20, 30)

In [25]:
a 

10

## Arrays

One of the most important containers in Julia are arrays. 

You will use tuples and arrays quite frequently in your code.  

An array is a multi-dimensional grid of values. 

Vectors and matrices, such as those from mathematics, are types of arrays in Julia. 

# One dimensional arrays (`vectors`)

A vector is a one-dimensional array. 

A column (row) vector is similar to a column (row) of values that you would have in Excel.

**Column** vector is a list of values separated with commas.

**Row** vector is a list of values separated with spaces.

In [33]:
col_vector = [1, "abc"] # example of a column vector (one dimensional array)

2-element Vector{Any}:
 1
  "abc"

In [34]:
not_col_vector = 1, "abc" # this creates a tuple! Remember the closing brackets for a vector. 

(1, "abc")

In [35]:
row_vector = [1 "abc"] # example of a row vector (one dimensional array)

1×2 Matrix{Any}:
 1  "abc"

# One dimensional arrays (`vectors`)

The big difference between a tuple and array is that we can change the values of the array. 

Below is an example where we change the first component of the array. 

This means that arrays are **mutable**. 

In [36]:
col_vector[1] = "def"

"def"

In [37]:
col_vector

2-element Vector{Any}:
 "def"
 "abc"

You can now see that the first element of the vector has changed from `1` to `def`. 

# Mutating with `push!()`

We can use the `push!()` function to add values to this vector. 

This grows the size of the vector. 

You might notice the `!` operator after `push`. 

This exclamation mark doesn't do anything particularly special in Julia. 

It is a coding convention to let the user know that the input is going to be altered / changed. 

In our case it lets us know that the vector is going to be mutated.

Let us illustrate with an example. 

# Mutating with `push!()`

Let us illustrate how the `push!()` functions works with an example. 

In [38]:
push!(col_vector, "hij") # col_vector is mutated here. It changes from 2 element vector to 3 element vector. 

3-element Vector{Any}:
 "def"
 "abc"
 "hij"

In [39]:
push!(col_vector, "klm") # We can repeat and it will keep adding to the vector.  

4-element Vector{Any}:
 "def"
 "abc"
 "hij"
 "klm"

# Creating arrays

One easy way to generate an array is using a **sequence**. 

We show multiple ways below to do this. 

**Note**: If you want to store the values in an array, you need to use the `collect()` function. 

In [42]:
seq_x = 1:10:21 # This is a sequence that starts at one and ends at 21 with an increment of 10. 

1:10:21

In [52]:
collect(seq_x) # Collects the values for the sequence into a vector

3-element Vector{Int64}:
  1
 11
 21

In [48]:
seq_y = range(1, stop = 21, length = 3) # Another way to do the same as above

1.0:10.0:21.0

In [50]:
seq_z = LinRange(1, 21, 3) # Still another way to do the same as above

3-element LinRange{Float64, Int64}:
 1.0,11.0,21.0

# Creating arrays 

For creation of arrays we frequently use functions like `zeros()`, `ones()`, `fill()` and `rand()`.

In [53]:
zeros(3) # Creates a column vector of zeros with length 3.

3-element Vector{Float64}:
 0.0
 0.0
 0.0

In [54]:
zeros(Int, 3) # We can specify that the zeros need to be of type `Int64`. 

3-element Vector{Int64}:
 0
 0
 0

In [55]:
ones(3) # Same thing as `zeros()`, but fills with ones

3-element Vector{Float64}:
 1.0
 1.0
 1.0

# Creating arrays 

For creation of arrays we frequently use functions like `zeros()`, `ones()`, `fill()` and `rand()`.

In [57]:
fill(2, 3) # Fill a three element column with the value of `2`

3-element Vector{Int64}:
 2
 2
 2

In [58]:
rand(3) # Values chosen will lie between zero and one. chosen with equal probability. 

3-element Vector{Float64}:
 0.9947097400925093
 0.6764130504332154
 0.01750999368374695

In [59]:
randn(3) # Values chosen randomly from Normal distribution 

3-element Vector{Float64}:
 -0.4202301726863895
  1.0213219464621448
  1.0034105723680253

# Two dimensional arrays (`matrices`)

We can also create matrices (two dimensional arrays) in Julia.

A matrix has both rows and columns. 

This would be like a table in Excel with rows and columns. 

To create a matrix we separate rows by spaces and columns by semicolons.

In [40]:
matrix_x = [1 2 3; 4 5 6; 7 8 9] # Rows separated by spaces, columns separated by semicolons.

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [41]:
matrix_y = [1 2 3;
            4 5 6;
            7 8 9] # Another way to write the matrix above

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

# Two dimensional arrays (`matrices`)

Those of you who have done statistics or mathematics know how important matrices are. 

Matrices are a fundamental part of linear algebra. 

Linear algebra is a super important area in mathematics (one of my favourites). 

There is an `optional` section on linear algebra in the full tutorial notes. 

If you want to do **Honours in Economics**, then I suggest getting comfortable with linear algebra!

# Creating two dimensional arrays

We can also create two dimensional arrays with `zeros()`, `ones()`, `fill()` and `rand()`. 
