# <span style="color:#2c061f"> Tutorial #1 </span>  

<br>

## <span style="color:#374045"> Introduction to Julia </span>


#### <span style="color:#374045"> Lecturer: </span> <span style="color:#d89216"> <br> Dawie van Lill (dvanlill@sun.ac.za) </span>

## Introduction

This is the first of 4 tutorials that are focused on basic computational methods in macroeconomics. These tutorials will provide some basic programming knowledge with application in macroeconomics. The tutorials are quite long and will take some time to work through. However, they are in notebook format, which means that they are interactive. This means you can play around with the code. This is supposed to be a hands-on experience. 

The first tutorial is supposed to show you the basics of the Julia programming language. We chose the Julia programming language because it is easy to learn and also very fast! There are other excellent languages, such as Python, R and Matlab, which are useful for economists. However, Julia will work for our purposes. Many of the lessons you learn here can be applied to other languages as well.

This notebook is meant to be used as a reference. In other words, I am not expecting you to remember everything in the notebook. The notebook introduces you to several concepts that you might need in the future. While this is a reference, it only covers the very basic components of the language. At the end of the tutorial you will see links to many more resources. With these resources you can explore the language even further.  


## Planned teaching outcomes

In this course we hope to look at different themes in computational macroeconomics. Most of modern macroeconomic research involves utilising computational methods, so it is wortwhile to get comfortable with some basic programming skills. The return on this investment is quite high. If you are interested in this type of work, feel free to contact me to talk about computational economics in Honours and Masters. 

**Note:** We currently don't offer modules at postgraduate level that explicitly teach computational methods. However, I am offering weekly sessions that cover the basics of programming and computation. I will create a class list where people can sign up for the sessions. These sessions are aimed at Honours and Masters students, but you are welcome to attend to see what all the hype is about!

Here are some of the focus areas

1. Fundamentals of Julia
2. Optimisation and the consumer problem
3. Simulation
4. Solow model

## Tutorial workflow

The tutorials will be pre-recorded so that you can go through the material on your own time. During the live tutorial session I will be answering questions and also going through some exercises. These will be both normal pen and pencil exercises and computer based exercises. 

## Installing Julia

The easiest way to install Julia is to go the [Downloads](https://julialang.org/downloads/) section on the website and install for your operating system. 

**Note**: If you are installing for Windows, then you need to check the box that says "Add to path". This is an important step. 

# Fundamentals

There are many great guides to that provide an introduction to Julia and programming. The QuantEcon website is an exceptional resource that can be used to teach yourself about computational economics. We will be borrowing some the material from their website in this section. The main difference with these notes is that they are not nearly as comprehensive and are only meant as a starting point for your journey. 

Before we get to a discussion on data types, let us try and run our first Julia program. For those that have done programming before, this normally entails writing a piece of code that gives us the output ``Hello World!``. In Julia this is super easy to do. 

## Data types

One of the best places to start with a discussion on a programming language is with data types. This might sound incredibly dull, but it is actually quite important to understand the different data types that can be used in a programming language and the functions that can be implemented on them. 

### Primitive data types

In [2]:
a = true

true

In [3]:
typeof(a)

Bool

The `typeof()` operator tells us what the data type a variable takes. In the case above we have a `Boolean` value, something that can either be `true` or `false`. 

In [4]:
b = 1 > 2 # What would b be in this case? Think about it for a second. 

false

In [5]:
typeof(b)

Bool

Now let's look at some other well known data types. 

In [6]:
typeof(122.0)

Float64

In [7]:
typeof(122)

Int64

Numbers are represented as floats and integers. Floating point numbers (floats) represent the way in which computers manifest real numbers.

With numbers in mind, we can treat the computer like a calculator. We can perform basic arithmetic operations. 

In [8]:
x = 2; y = 10

10

In [9]:
x * y

20

In [10]:
x ^ y

1024

In [11]:
y / x

5.0

In [12]:
2x - 3y

-26

In [13]:
x // y

1//5

## Comparison via Boolean operators

In [16]:
x = 3; y = 2; 

In [17]:
x < y

false

In [18]:
x <= y

false

In [19]:
x != y

true

In [20]:
x == y

false

In [21]:
z = x < y

false

In [22]:
typeof(z)

Bool

## Containers


In [33]:
x = [1, "abc"]

2-element Vector{Any}:
 1
  "abc"

In [25]:
length(x)

2

In [26]:
length(1:5)

5

In [27]:
x[1]

1

In [28]:
x[2]

"abc"

In [34]:
x[1] = "def"

"def"

In [37]:
x
typeof(x)

Vector{Any} (alias for Array{Any, 1})

In [36]:
push!(x, "new") 

3-element Vector{Any}:
 "def"
 "abc"
 "new"

In [40]:
x = ("foo", "bar") # Immutable

("foo", "bar")

In [41]:
y = ("foo", 2)

("foo", 2)

In [42]:
typeof(x)

Tuple{String, String}

In [43]:
word, val = x # Unpacking a tuple

("foo", "bar")

In [44]:
word

"foo"

In [45]:
val

"bar"

## Slicing

In [36]:
x = [0, 1, 2, 3, 4, 5]

6-element Vector{Int64}:
 0
 1
 2
 3
 4
 5

In [37]:
x[1:3]

3-element Vector{Int64}:
 0
 1
 2

In [38]:
x[1:4]

4-element Vector{Int64}:
 0
 1
 2
 3

In [39]:
x[end]

5

In [49]:
x = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [50]:
y = x

3-element Vector{Int64}:
 1
 2
 3

In [51]:
y[1] = 2

2

In [52]:
x 

3-element Vector{Int64}:
 2
 2
 3

In [53]:
x == y

true

In [55]:
pointer(x)

Ptr{Int64} @0x00007f9fc984fc90

In [56]:
pointer(y)

Ptr{Int64} @0x00007f9fc984fc90

In [54]:
z = copy(x)

3-element Vector{Int64}:
 2
 2
 3

In [57]:
x == z

true

In [58]:
z[2] = 5

5

In [59]:
x == z

false

In [60]:
z

3-element Vector{Int64}:
 2
 5
 3

In [61]:
x

3-element Vector{Int64}:
 2
 2
 3

In [62]:
pointer(x)

Ptr{Int64} @0x00007f9fc984fc90

In [63]:
pointer(z)

Ptr{Int64} @0x00007f9fc9a27150

In [64]:
x = [1, 2, 3] 

3-element Vector{Int64}:
 1
 2
 3

In [65]:
y = x[:]

3-element Vector{Int64}:
 1
 2
 3

In [66]:
y[1] = 2

2

In [69]:
pointer(y)

Ptr{Int64} @0x00007f9fc9187150

In [70]:
pointer(x) # What is happening here? Why is the x value not changed when y changed?

Ptr{Int64} @0x00007f9fc8fd38d0

## Conditionals and loops

In [72]:
x = 1

if x < 2
    print("first")
elseif x > 4
    print("second")
elseif x < 0
    print("third")
else
    print("fourth")
end 

first

Avoid repeating code at ALL COSTS. Do not repeat yourself. This is the DRY principle in coding. 

In [73]:
x = [0,1,2,3,4]

5-element Vector{Int64}:
 0
 1
 2
 3
 4

In [71]:
y_1 = [] # empty array (list in python)

Any[]

In [73]:
append!(y_1, x[1] ^ 2)
append!(y_1, x[2] ^ 2)
append!(y_1, x[3] ^ 2)
append!(y_1, x[4] ^ 2)
append!(y_1, x[5] ^ 2)

5-element Vector{Any}:
  0
  1
  4
  9
 16

In [76]:
y_2 = []

Any[]

In [77]:
for i in x
    append!(y_2, i ^ 2)
    println(y_2)
end

Any[0]
Any[0, 1]
Any[0, 1, 4]
Any[0, 1, 4, 9]
Any[0, 1, 4, 9, 16]


In [5]:
y_3 = []

Any[]

In [6]:
for i in 0:4
    append!(y_3, i ^ 2)
    println(y_3)
end

Any[0]
Any[0, 1]
Any[0, 1, 4]
Any[0, 1, 4, 9]
Any[0, 1, 4, 9, 16]


In [10]:
y_4 = [i ^ 2 for i in x] # array comprehension -- we will mention this again later on

5-element Vector{Int64}:
  0
  1
  4
  9
 16

## Iterables

In [77]:
actions = ["watch Netflix", "like 318 homework"]

2-element Vector{String}:
 "watch Netflix"
 "like 318 homework"

In [80]:
for action in actions
    println("Peter doesn't $action")
end

Peter doesn't watch Netflix
Peter doesn't like 318 homework


In [86]:
for i in 1:3
    println(i)
end

1
2
3


In [87]:
x_values = 1:5

1:5

In [88]:
for x in x_values
    println(x * x)
end

1
4
9
16
25


In [89]:
for i in eachindex(x_values)
    println(x_values[i] * x_values[i])
end

1
4
9
16
25


In [90]:
?eachindex

search: eachindex



```
eachindex(A...)
```

Create an iterable object for visiting each index of an `AbstractArray` `A` in an efficient manner. For array types that have opted into fast linear indexing (like `Array`), this is simply the range `1:length(A)`. For other array types, return a specialized Cartesian range to efficiently index into the array with indices specified for every dimension. For other iterables, including strings and dictionaries, return an iterator object supporting arbitrary index types (e.g. unevenly spaced or non-integer indices).

If you supply more than one `AbstractArray` argument, `eachindex` will create an iterable object that is fast for all arguments (a [`UnitRange`](@ref) if all inputs have fast linear indexing, a [`CartesianIndices`](@ref) otherwise). If the arrays have different sizes and/or dimensionalities, a DimensionMismatch exception will be thrown.

# Examples

```jldoctest
julia> A = [1 2; 3 4];

julia> for i in eachindex(A) # linear indexing
           println(i)
       end
1
2
3
4

julia> for i in eachindex(view(A, 1:2, 1:1)) # Cartesian indexing
           println(i)
       end
CartesianIndex(1, 1)
CartesianIndex(2, 1)
```


In [83]:
countries = ("Japan", "Korea", "China")

("Japan", "Korea", "China")

In [84]:
cities = ("Tokyo", "Seoul", "Beijing")

("Tokyo", "Seoul", "Beijing")

In [93]:
for (country, city) in zip(countries, cities)
    println("The capital of $country is $city")
end

The capital of Japan is Tokyo
The capital of Korea is Seoul
The capital of China is Beijing


In [97]:
for (i, country) in enumerate(countries)    
    println(i, " ", country)

    #city = cities[i]
    #println("The capital of $country is $city")

end

1 Japan
2 Korea
3 China


## Comprehensions

In [95]:
doubles = [ 2i for i in 1:4 ]

4-element Vector{Int64}:
 2
 4
 6
 8

In [96]:
[ i + j for i in 1:3, j in 4:6 ]

3×3 Matrix{Int64}:
 5  6  7
 6  7  8
 7  8  9

## Breaks

In [33]:
y_array = []
x_array = collect(0:9)

10-element Vector{Int64}:
 0
 1
 2
 3
 4
 5
 6
 7
 8
 9

In [32]:
for (i, x) in enumerate(x_array)
    
    if i == 1
        continue
    elseif i == 4
        break
    end
    
    append!(y_array, x^2)
end

println(y_array)

Any[4, 9]


## User defined functions (important section)

In [100]:
function f(x) # function header
    return x ^ 2 # body of the function
end

f (generic function with 1 method)

In [101]:
f(2)

4

In [102]:
g(x) = x ^ 2

g (generic function with 1 method)

In [103]:
g(2)

4

In [38]:
h = (x) -> x ^ 2 # Lambda or anonymous function

#5 (generic function with 1 method)

In [39]:
h(2)

4

In [116]:
function k(x, y)
    """ This is a function that squares things 
    
    k(x, y; a) 

    a is this keyword argument
    """
    return x ^ 2 + y ^ 2
end

k (generic function with 1 method)

In [106]:
k(2, 2)

8

In [107]:
function m(x, y)
    z = x ^ 2
    q = y ^ 2
    
    return z, q
end

m (generic function with 1 method)

In [108]:
z, q = m(2, 2)

(4, 4)

In [109]:
z

4

In [110]:
q

4

## Scope

In [111]:
a = 2 # global variable

2

In [112]:
function f(x)
    return x ^ a
end

f (generic function with 1 method)

In [5]:
function g(x; a = 2)
    return x ^ a
end

g (generic function with 1 method)

In [6]:
function h(x)
    a = 2 # a is local 
    return x ^ a
end

h (generic function with 1 method)

In [113]:
f(2), g(2), h(2)

(4, 4, 4)

In [114]:
a += 1

3

In [115]:
f(2), g(2), h(2)

(8, 4, 4)

Never rely on global variables! 

## Keyword arguments

In [48]:
function p(x, y; a = 2, b = 2)
    return x ^ a + y ^ b
end

p (generic function with 1 method)

In [49]:
p(2, 4)

20

In [50]:
p(2, 4, b = 4)

260

In [51]:
p(2, 4, a = 4)

32

## Floating point numbers

Quick introduction to the idea of floating point numbers

In [117]:
x = 0.1

0.1

In [118]:
10 * x

1.0

Simple sums don't always give the answers that you would expect.

In [124]:
x + x + x + x + x + x + x + x + x + x

0.9999999999999999

Another surprising result

In [125]:
0.1 == 0.10000000000000001

true

Comparison of floating point numbers is therefore problematic

In [126]:
a = 0.001
b = 11.11
c = 1000
test = (a*c)/(b*c) == a/b

false