# Tutorial 1: Introduction to programming with Julia

NB -- Consider an economic example for this first tutorial so that it isn't so completely dry. 


This is the first of 4 tutorials that are focused on very basic computational methods in macroeconomics. This is a short tutorial that is supposed to show you the basics of the Julia programming language. At the end of the tutorial you will see links to many more resources. These tutorials are a short introduction to the topics, so that you can get a feeling for what is on offer. 

## Planned teaching outcomes

In this course we hope to look at different themes in computational macroeconomics. Most of modern macroeconomic research involves utilising computational methods, so it is wortwhile to get comfortable with some basic programming skills. The return on this investment is quite high. If you are interested in this type of work, feel free to contact me to talk about computational economics in Honours and Masters. 

Here are some of the focus areas

- Introduction to programming with Julia
- Optimisation and the consumer problem
- Simulation (optional)
- Solow model (optional)

Ideally, I would also like to teach you about version control through Git, but I realise that this might too much to handle in such a short time. I will provide some links to getting started with Git at the bottom of the page. 

# Tutorial workflow

The tutorials will be pre-recorded so that you can go through the material on your own time. During the tutorial session I will be answering questions and also going through some exercises. These will be both normal pen and pencil exercises and computer based exercises. 

# Fundamentals

There are many great guides to that provide an introduction to Julia and programming. The QuantEcon website is an exceptional resource that can be used to teach yourself about computational economics. We will be borrowing some the material from their website in this section. The main difference with these notes is that they are not nearly as comprehensive and are only meant as a starting point for your journey. 

## Data types

One of the best places to start with a discussion on a programming language is with data types. This might sound incredibly dull, but it is actually quite important to understand the different data types that can be used in a programming language and the functions that can be implemented on them. 

### Primitive data types

In [2]:
a = true

true

In [3]:
typeof(a)

Bool

The `typeof()` operator tells us what the data type a variable takes. In the case above we have a `Boolean` value, something that can either be `true` or `false`. 

In [4]:
b = 1 > 2 # What would b be in this case? Think about it for a second. 

false

In [5]:
typeof(b)

Bool

Now let's look at some other well known data types. 

In [6]:
typeof(122.0)

Float64

In [7]:
typeof(122)

Int64

Numbers are represented as floats and integers. Floating point numbers (floats) represent the way in which computers manifest real numbers.

With numbers in mind, we can treat the computer like a calculator. We can perform basic arithmetic operations. 

In [8]:
x = 2; y = 10

10

In [9]:
x * y

20

In [10]:
x ^ y

1024

In [11]:
y / x

5.0

In [12]:
2x - 3y

-26

In [13]:
x // y

1//5

## Comparison via Boolean operators

In [16]:
x = 3; y = 2; 

In [17]:
x < y

false

In [18]:
x <= y

false

In [19]:
x != y

true

In [20]:
x == y

false

In [21]:
z = x < y

false

In [22]:
typeof(z)

Bool

## Containers


In [23]:
x = [1, "abc"]

2-element Vector{Any}:
 1
  "abc"

In [24]:
length(x)

2

In [25]:
x[1]

1

In [26]:
x[2]

"abc"

In [27]:
x[1] = "def"

"def"

In [28]:
x

2-element Vector{Any}:
 "def"
 "abc"

In [29]:
push!(x, "new element") # difference with append! ??

3-element Vector{Any}:
 "def"
 "abc"
 "new element"

In [30]:
x = ("foo", "bar") # Immutable

("foo", "bar")

In [31]:
y = ("foo", 2)

("foo", 2)

In [32]:
typeof(x)

Tuple{String, String}

In [33]:
word, val = x # Unpacking a tuple

("foo", "bar")

In [34]:
word

"foo"

In [35]:
val

"bar"

## Slicing

In [36]:
x = [0, 1, 2, 3, 4, 5]

6-element Vector{Int64}:
 0
 1
 2
 3
 4
 5

In [37]:
x[1:3]

3-element Vector{Int64}:
 0
 1
 2

In [38]:
x[1:4]

4-element Vector{Int64}:
 0
 1
 2
 3

In [39]:
x[end]

5

In [40]:
x = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [41]:
y = x

3-element Vector{Int64}:
 1
 2
 3

In [42]:
y[1] = 2

2

In [43]:
x # x is also changed here!

3-element Vector{Int64}:
 2
 2
 3

In [44]:
x == y

true

In [45]:
pointer(x)

Ptr{Int64} @0x00007f3d5240be70

In [46]:
pointer(y)

Ptr{Int64} @0x00007f3d5240be70

In [53]:
z = copy(x)

3-element Vector{Int64}:
 2
 2
 3

In [54]:
x == z

true

In [56]:
z[2] = 5

5

In [57]:
x == z

false

In [58]:
z

3-element Vector{Int64}:
 2
 5
 3

In [59]:
x

3-element Vector{Int64}:
 2
 2
 3

In [60]:
pointer(x)

Ptr{Int64} @0x00007f3d5240be70

In [61]:
pointer(z)

Ptr{Int64} @0x00007f3d51bc3ab0

In [62]:
x = [1, 2, 3] 

3-element Vector{Int64}:
 1
 2
 3

In [63]:
y = x[:]

3-element Vector{Int64}:
 1
 2
 3

In [64]:
y[1] = 2

2

In [65]:
y

3-element Vector{Int64}:
 2
 2
 3

In [66]:
x # What is happening here? Why is the x value not changed when y changed?

3-element Vector{Int64}:
 1
 2
 3

## Conditionals and loops

In [68]:
x = 3

if x < 2
    print("first")
elseif x > 4
    print("second")
elseif x < 0
    print("third")
else
    print("fourth")
end 

fourth

Avoid repeating code at ALL COSTS. Do not repeat yourself. This is the DRY principle in coding. 

In [70]:
x = [0,1,2,3,4]

5-element Vector{Int64}:
 0
 1
 2
 3
 4

In [71]:
y_1 = [] # empty array (list in python)

Any[]

In [73]:
append!(y_1, x[1] ^ 2)
append!(y_1, x[2] ^ 2)
append!(y_1, x[3] ^ 2)
append!(y_1, x[4] ^ 2)
append!(y_1, x[5] ^ 2)

5-element Vector{Any}:
  0
  1
  4
  9
 16

In [76]:
y_2 = []

Any[]

In [77]:
for i in x
    append!(y_2, i ^ 2)
    println(y_2)
end

Any[0]
Any[0, 1]
Any[0, 1, 4]
Any[0, 1, 4, 9]
Any[0, 1, 4, 9, 16]


In [79]:
y_2

5-element Vector{Any}:
  0
  1
  4
  9
 16

## Iterables

In [80]:
actions = ["watch Netflix", "like 318 homework"]

2-element Vector{String}:
 "watch Netflix"
 "like 318 homework"

In [83]:
for action in actions
    println("Peter doesn't $action")
end

Peter doesn't watch Netflix
Peter doesn't like 318 homework


In [86]:
for i in 1:3
    println(i)
end

1
2
3


In [87]:
x_values = 1:5

1:5

In [88]:
for x in x_values
    println(x * x)
end

1
4
9
16
25


In [89]:
for i in eachindex(x_values)
    println(x_values[i] * x_values[i])
end

1
4
9
16
25


In [90]:
?eachindex

search: eachindex



```
eachindex(A...)
```

Create an iterable object for visiting each index of an `AbstractArray` `A` in an efficient manner. For array types that have opted into fast linear indexing (like `Array`), this is simply the range `1:length(A)`. For other array types, return a specialized Cartesian range to efficiently index into the array with indices specified for every dimension. For other iterables, including strings and dictionaries, return an iterator object supporting arbitrary index types (e.g. unevenly spaced or non-integer indices).

If you supply more than one `AbstractArray` argument, `eachindex` will create an iterable object that is fast for all arguments (a [`UnitRange`](@ref) if all inputs have fast linear indexing, a [`CartesianIndices`](@ref) otherwise). If the arrays have different sizes and/or dimensionalities, a DimensionMismatch exception will be thrown.

# Examples

```jldoctest
julia> A = [1 2; 3 4];

julia> for i in eachindex(A) # linear indexing
           println(i)
       end
1
2
3
4

julia> for i in eachindex(view(A, 1:2, 1:1)) # Cartesian indexing
           println(i)
       end
CartesianIndex(1, 1)
CartesianIndex(2, 1)
```


In [91]:
countries = ("Japan", "Korea", "China")

("Japan", "Korea", "China")

In [92]:
cities = ("Tokyo", "Seoul", "Beijing")

("Tokyo", "Seoul", "Beijing")

In [93]:
for (country, city) in zip(countries, cities)
    println("The capital of $country is $city")
end

The capital of Japan is Tokyo
The capital of Korea is Seoul
The capital of China is Beijing


In [94]:
for (i, country) in enumerate(countries)
    city = cities[i]
    println("The capital of $country is $city")
end

The capital of Japan is Tokyo
The capital of Korea is Seoul
The capital of China is Beijing


## Comprehensions

In [95]:
doubles = [ 2i for i in 1:4 ]

4-element Vector{Int64}:
 2
 4
 6
 8

In [96]:
[ i + j for i in 1:3, j in 4:6 ]

3×3 Matrix{Int64}:
 5  6  7
 6  7  8
 7  8  9

## User defined functions (important section)