# <span style="color:#2c061f"> Macro 318: Tutorial #1 </span>  

<br>

## <span style="color:#374045"> Introduction to Programming with Julia </span>


#### <span style="color:#374045"> Lecturer: </span> <span style="color:#d89216"> <br> Dawie van Lill (dvanlill@sun.ac.za) </span>

## Introduction

This is the first of four tutorials that are focused on basic computational methods in macroeconomics. These tutorials will provide some basic programming knowledge with application in macroeconomics. The tutorials are quite long and will take some time to work through. However, they are in notebook format, which means that they are interactive. This means you can play around with the code. This is supposed to be a hands-on experience. 

The first tutorial is supposed to show you the basics of the Julia programming language. We chose the Julia programming language because it is easy to learn and also very fast! There are other excellent languages, such as Python, R and Matlab, which are useful for economists. However, Julia will work for our purposes. Many of the lessons you learn here can be applied to other languages as well.

This notebook is meant to be used as a reference. In other words, I am not expecting you to remember everything in the notebook. The notebook introduces you to several concepts that you might need in the future. While this is a reference, it only covers the very basic components of the language. At the end of the tutorial you will see links to many more resources. With these resources you can explore the language even further.  


## Planned teaching outcomes

In this course we hope to look at different themes in computational macroeconomics. Most of modern macroeconomic research involves utilising computational methods, so it is wortwhile to get comfortable with some basic programming skills. The return on this investment is quite high. If you are interested in this type of work, feel free to contact me to talk about computational economics in Honours and Masters. 

**Note:** We currently don't offer modules at postgraduate level that explicitly teach computational methods. However, I am offering weekly sessions that cover the basics of programming and computation. I will create a class list where people can sign up for the sessions. These sessions are aimed at Honours and Masters students, but you are welcome to attend to see what all the hype is about!

Here are some of the focus areas

1. Fundamentals of programming
2. Optimisation and the consumer problem
3. Solow model 
4. Simulation + data work

## Tutorial workflow

The tutorials will be pre-recorded so that you can go through the material on your own time before the live tutorial session. During the live tutorial session I will be answering questions and also going through some exercises. These will be both normal pen and pencil exercises and computer based exercises.

## Running the notebooks

The current notes are put together in a Jupyter notebook.

For the purpose of this course you will run the notebooks online (this doesn't require you to install Python, Julia or Jupyter on your system). You can also run these files locally on your computer without the need for the internet, but that requires an installation procedure that will be too difficult to explain to 250+ students.

I will make a brief video on how to install Julia, Python, Jupyter and VS Code for those that are interested. However, this is completely optional. 



## Topics for the tutorial

Below are the topics for the tutorial

1. Data types
2. Control flow
3. Functions
4. Floating point arithmetic

Most of these topics are covered in introductory undergraduate computer science courses, so if you are a CS student then you can quickly skim for the Julia syntax. If you are comfortable with a modern programming language like Python then everything here will feel somewhat familiar.


# Fundamentals

There are many great guides to that provide an introduction to Julia and programming. The QuantEcon website is an exceptional resource that can be used to teach yourself about computational economics. We will be borrowing some the material from their website in this section. The main difference with these notes is that they are not nearly as comprehensive and are only meant as a starting point for your journey. 

Before we start our discussion, let us try and run our first Julia program. For those that have done programming before, this normally entails writing a piece of code that gives us the output ``Hello World!``. In Julia this is super easy to do. 

In [ ]:
println("Hello World!")

## Adding packages

As an aside, Julia has many package. If we want to include a specific package then we can do the following,

`import Pkg`

`Pkg.add("PackageName")`

`using PackageName`

In [3]:
import Pkg

In [12]:
Pkg.add("LinearAlgebra") # This will allow for prettier printing. 

   Resolving package versions...
    Updating `~/.julia/environments/v1.7/Project.toml`
  [37e2e46d] + LinearAlgebra
  No Changes to `~/.julia/environments/v1.7/Manifest.toml`


In [13]:
using LinearAlgebra

## Variables

A good place to start our journey is with variables. A variable in a programming language is going to be some sort of symbol that we assign some value. Let us use a concrete example to illustrate. 

In [ ]:
x = 2 # assign the value of 2 to the variable x

The value `2` is now bound to `x` in the computer's memory. We can now work with `x` as if it represents the value of `2`. 

In [ ]:
x + 2

Generally when we name variables they will start with letters and in Julia the preference is to use snake case. This means using underscores between words. As an example `new_variable` instead of `newVariable`. The latter is an example of camel case. 

**Note**: `const x = 2` will define a constant variable. We will get back to this point later in the session. 

## Data types

One of the best places to start with a discussion on a programming language is with data types. This might sound incredibly dull, but it is actually quite important to understand the different data types that can be used in a programming language and the functions that can be implemented on them. 

### Primitive data types

There are several important data types that are at the core of computing. Some of these include, 

- **Booleans**: true and false
- **Integers**: -3, -2, -1, 0, 1, 2, 3, etc.
- **Floating point numbers**: 3.14, 2.95, 1.0, etc.
- **Strings**: "abc", "cat", "hello there"
- **Characters**: 'f', 'c', 'u'

We start our discussion with Booleans, these are `true` / `false` values.

In [ ]:
a = true

In [ ]:
typeof(a)

The `typeof()` operator tells us what the data type a variable takes. In the case above we have a `Boolean` value. Now let's look at some other well known data types. 

In [ ]:
typeof(122)

In [ ]:
typeof(122.0)

Numbers are represented as floats and integers. Floating point numbers (floats) represent the way in which computers manifest real numbers.

With numbers in mind, we can treat the computer like a calculator. We can perform basic arithmetic operations. Operators perform operations. These common operators are called the **arithmetic operators**. 

In [ ]:
x = 2; y = 10

In [ ]:
x * y

In [ ]:
x ^ y

In [ ]:
y / x # note: division converts integers to floats

In [ ]:
2x - 3y

In [ ]:
x // y

Another important data type is the String (and Character)

In [ ]:
typeof("Hello Class!")

In [ ]:
typeof('h')

Some of the operators used on floats and integers above can also be used on strings and characters. 

In [ ]:
x = "abc"; y = "def"

In [ ]:
x * y # concatenation

In [ ]:
x ^ 2 # multiples

Another important class of operators that we will often encounter are the **augmentation operators**. This will be especially important in the section on control flow. 

In [ ]:
x = 3

In [ ]:
x += 1 # same as x = x + 1

In [ ]:
x *= 2 # same as x = x * 2

In [ ]:
x /= 2 # same as x = x / 2 

Now that we have talked about the basic data types, it is important to talk about the different operators that are supported in Julia. We have already used some of the mathematical operators, such as multiplication and division when it came to floating point numbers. However, Julia has another set of common operators that work on Booleans. 

In [ ]:
!true # negation operation

In [ ]:
x = true; y = true

In [ ]:
x && y # and operator. Returns true if x and y are both true, otherwise false

In [ ]:
x || y # or operator. Returns true if x aor y is true, otherwise false

Another important class of operators are the comparison operators. These help to generate true and false values for our conditional statements that we see later in the tutorial. 

In [ ]:
x = 3; y = 2; 

In [ ]:
x < y

In [ ]:
x <= y

In [ ]:
x != y

In [ ]:
x == y

In [ ]:
z = x < y

### Type conversion

It is possible to convert the type of one variable to another type. One could, as an example convert a float to string, or float to integer. 

In [ ]:
x = 1

In [ ]:
y = string(x)

In [ ]:
z = float(x)

In [ ]:
y = string(z)

It is not possible to convert a string to an integer. So this means there are some limitations to conversion. The following bit of code uses exception handling, don't worry too much about it for now. We will talk about this some more in the section on control flow. [Here](https://docs.julialang.org/en/v1/manual/control-flow/#Exception-Handling) is a link that goes into some more detail on the topic. 

In [ ]:
try
    x = Int("22")
    println("This conversion is possible")
    println("The resulting value is $x")
catch
    println("This conversion is not possible")
end

This raises the question as to whether a boolean variables can be converted to an integer? Write a bit of code, given what is provided above to try and check this. Here is some code to get started. 

In [ ]:
try 
    x = Int() # fill in the missing conversion here
    println("This conversion is possible")
    println("The resulting value is $x")
catch
    println("This conversion is not possible")
end

### Containers

There are several types of containers, such as arrays and tuples, in Julia. We explore some of the most commonly used containers here. 

Note that we have both mutable and immutable types of containers in Julia. Mutable means that the value within that container can be changed, whereas immutable refers to the fact that values cannot be altered. 

### Tuples

Let us start with one of the basic types of containers, which are referred to as tuples. These containers are immutable (can't change the values in the container), ordered and of a fixed length. Consider the following example of a tuple,

In [ ]:
x = (10, 20, 30)

We can access the first component of a tuple in the following way, 

In [ ]:
x[1]

We can generally unpack a tuple in the following fashion, 

In [ ]:
a, b, c = x

In [ ]:
a

#### Named tuples (optional)

It is also possible to provide names to each position of a named tuple. Here is an example of a named tuple. 

In [ ]:
x = (first = 'a', second = 100, third = (1, 2, 3))

In [ ]:
x.third # provides access to the third element in the tuple (which in this case is another tuple)

In [ ]:
x[:third] # equivalent to x.third

You can merge named tuples to add new elements to the tuple. Let us say that you want to add the sentence "Programming is awesome!" to the named tuple, you can do it is as follows, 

In [ ]:
y = (fourth = "Programming is awesome!", ) # note the comma at the end, if you don't have it, then this won't work. 

In [ ]:
merge(x, y)

### Arrays

One of the most important containers in Julia are arrays. You will use tuples and arrays quite frequently in your code. Vectors and matrices, such as those from mathematics, are types of arrays in Julia. Let us start with the idea of a vector. 

In Julia, we can create a vector by surrounding a value by brackets and separating the values with commas.

In [18]:
vector_x = [1, "abc"] # example of a vector (one dimensional array)

2-element Vector{Any}:
 1
  "abc"

In [ ]:
typeof(vector_x)

As with tuples, we can access the elements of the vector in the following way, 

In [ ]:
vector_x[1]

The big difference between a tuple and array is that we can change the values of the array. Below is an example where we change the first component of the array. This means that arrays are mutable. 

In [ ]:
vector_x[1] = "def"

In [ ]:
vector_x

We can use the `push!()` function to add values to this vector. This grows the size of the vector. You might notice the `!` operator after `push`. This exclamation mark doesn't do anything particularly special in Julia. It is a coding convention to let the user know that the input is going to be altered / changed. In our case it lets us know that the vector is going to be mutated. Let us illustrate.  

In [ ]:
push!(vector_x, "hij") # vector_x is mutated here. It changes from 2 element vector to 3 element vector. 

We can also create matrices (which are rectangular arrays) in the following way,

In [1]:
matrix_x = [1 2 3; 4 5 6; 7 8 9] # rows separated by spaces, columns separated by semicolons.

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [2]:
matrix_y = [1 2 3;
            4 5 6;
            7 8 9] # another way to write the matrix above

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

Another important object in Julia is a sequence. We can create a sequence as follows, 

In [28]:
seq_x = 1:10:21 # this is a sequence that starts at one and ends at 21 with an increment of 10. 

1:10:21

In order to collect the values of the sequence into a vector, we can use the `collect` function. 

In [29]:
collect(seq_x)

3-element Vector{Int64}:
  1
 11
 21

### Convenience functions

There are several convenience functions that can be applied to arrays. We can look at the length of an array by using the `length` function. 

In [ ]:
length(vector_x) # provides information on how long the vector is

In [ ]:
length(matrix_x)

In [ ]:
size(vector_x) # provides information in the format of a tuple. This is more useful for multidimensional arrays

In [ ]:
size(matrix_x) # we can now see the size of the matrix as 3 x 3

In [ ]:
zeros(3) # provides a vector of zeros with length 3.

Note that the default type for the zeros in the vector above is `Float64`. If we wanted we could specify these values to be integers as follows, 

In [ ]:
zeros(Int, 3)

In [ ]:
ones(3) # same thing as above, but fills with ones

Sometimes we want to create vectors that are filled with random values. The simplest function is `rand()`, which selects random values from the uniform distribution on the interval between zero and one. This means that the each value is picked with equal probability in the interval between zero and one. 

In [ ]:
rand(3) # values chosen will lie between zero and one. chosen with equal probability. 

An alternative is to pick values according to the standard [Normal distribution](https://en.wikipedia.org/wiki/Normal_distribution), instead of the uniform distribution as above. The Normal distribution is a distribution which is symmetric around zero, with majority of values lying within three standard deviations of the mean (which is zero). This means that this random value selection tool will select values to the right and left of zero on the real line. In other words, it will select both positive and negative values with about 99% of values falling within three standard deviations from the mean. 

In [ ]:
randn(3)

### Slicing


Remember from before that we can extract value from containers. 

In [ ]:
vector_x[1] # extract the first value

In [ ]:
matrix_x[2, 2] # retrieve the value in the second row and second column of the matrix

In [19]:
vector_x[1:2] # gets the first two values of the vector

2-element Vector{Any}:
 1
  "abc"

In [ ]:
vector_x[2:end] # extracts all the values from the second to the end of the vector

In [ ]:
vector_x[:, 1] # provides all the values of the first column

In [ ]:
vector_x[1, :] # provides all the values from the first row

Next let's move on to a brief discussion on linear algebra. 

### Basic linear algebra operations

Linear algebra is an incredibly useful branch of mathematics that I would highly recommend students invest time in. If you are interested in the more computational or statistical side of economics then you need to learn some linear algebra. For a more detailed look at linear algebra, the best place to go is the [QuantEcon website](https://julia.quantecon.org/tools_and_techniques/linear_algebra.html). The material there is a bit more advanced than we are covering for this course, but it is worthwhile working through if you are interested in doing postgraduate work in economics.  

Linear algebra entails operations with matrices and vectors at its core, so let us show some basic commands. 

In [14]:
Q = matrix_x

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

We start with multiplication and addition operations on arrays. 

One can multiply a matrix with a scalar and also add a scalar to each component of a matrix.

One can also multiply matrices together when they have the same dimension. 

It is also possible to multiply the transpose of a matrix with itself (or another matrix). 

All of these operations will have specific applicability in certain situations. I am not speaking at this stage as to why we are doing this, but simply stating the conditions under which we can perform these operations. 

In [24]:
2 * Q # multiply matrix with scalar. All elements of matrix are multiplied by 2. 

3×3 Matrix{Int64}:
  2   4   6
  8  10  12
 14  16  18

In [25]:
2 + Q  # Look at the first two line of the error message below 

MethodError: MethodError: no method matching +(::Int64, ::Matrix{Int64})
For element-wise addition, use broadcasting with dot syntax: scalar .+ array
Closest candidates are:
  +(::Any, ::Any, !Matched::Any, !Matched::Any...) at /usr/share/julia/base/operators.jl:655
  +(::T, !Matched::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at /usr/share/julia/base/int.jl:87
  +(::Union{Int16, Int32, Int64, Int8}, !Matched::BigInt) at /usr/share/julia/base/gmp.jl:535
  ...

The error message above (`no method matching +(::Int64, ::Matrix{Int64})`) is telling us in the first line that there is no way to add an integer to a matrix. It is basically saying that the plus operator does not know what to do when the types of the inputs are an integer and matrix. This is why types play such an important role in Julia. The plus operator looks at the types to decide what action to perform. If there is no action corresponding to the input types provided then we get a `MethodError`. 

In order to add the value of `2` to every component of the matrix, we need to `broadcast` the value of `2` across all the matrix components. We can think about this as adding the value of `2` elementwise. 

The error message here even tells us that this is the way to solve the problem, 

On the second line of the error message we have: For element-wise addition, use broadcasting with dot syntax: scalar .+ array

Broadcasting can be done in Julia using the `.` operator. 

In [27]:
2 .+ Q # notice the `.` in front of the plus sign. 

3×3 Matrix{Int64}:
 3   4   5
 6   7   8
 9  10  11

In [22]:
Q*Q # matrix multiplication

3×3 Matrix{Int64}:
  30   36   42
  66   81   96
 102  126  150

We can take the transpose of a matrix in two ways with Julia

In [20]:
Q' # technically the adjoint

3×3 adjoint(::Matrix{Int64}) with eltype Int64:
 1  4  7
 2  5  8
 3  6  9

In [21]:
transpose(Q)

3×3 transpose(::Matrix{Int64}) with eltype Int64:
 1  4  7
 2  5  8
 3  6  9

In [16]:
Q'Q # multiplication of the transpose with the original matrix

3×3 Matrix{Int64}:
 66   78   90
 78   93  108
 90  108  126

## Control flow

In this section we will be looking at conditional statements and loops. 

Conditional statements provide branches to a program depending on a certain condition. The most recognisable conditional statement is the if-else statement. Consider the example below. 

In [ ]:
x = 1

if x < 2
    print("first")
elseif x > 4
    print("second")
elseif x < 0
    print("third")
else
    print("fourth")
end 

One can also represent conditional statements via a ternary operator, this is often more compact. 

In [ ]:
x, y, z = 1, 3, true

Can you make sense of what the expression below is saying? If you don't know then that is completely understandable. 

In [ ]:
z ? x : y 

The above can also be written as follows, in a more lengthy if-else fashion

In [ ]:
if z 
    x
else 
    y
end

A shorter, and perhaps more understandable way would be the following. 

In [ ]:
ifelse(z, x, y) # This means, return x if z is true, otherwise return y. 

### Loops

Avoid repeating code at ALL COSTS. Do not repeat yourself. This is the DRY principle in coding. 

In [ ]:
x = [0,1,2,3,4]

In [ ]:
y_1 = [] # empty array (list in python)

In [ ]:
append!(y_1, x[1] ^ 2)
append!(y_1, x[2] ^ 2)
append!(y_1, x[3] ^ 2)
append!(y_1, x[4] ^ 2)
append!(y_1, x[5] ^ 2)

Generally we will encounter two types of loops. We get `for` loops and `while` loops. We will mostly focus on `for` loops here. They are best in cases when you know exactly how many times you want to loop. On the other hand, `while` loops are used when you want to keep looping till something in particular happens (some condition is met). 

Let us try and fill our array using a `for` loop. 

In [ ]:
y_2 = []

In the following loop we will have 5 iterations. The array `y_2` will be altered. We refer to `y_2` as a **global** variable. We will talk about variable scope, local and global variables, later when we get to functions. 

In [ ]:
for i in x
    append!(y_2, i ^ 2)
    println(y_2)
end

In [ ]:
y_3 = []

In [ ]:
for i in 0:4
    append!(y_3, i ^ 2)
    println(y_3)
end

In [ ]:
y_4 = [i ^ 2 for i in x] # array comprehension -- we will mention this again later on

We could also use double for loops! This means that we nest a loop within another loop. This is used a lot in practice. Let us look at the following code to fill the entries of a matrix. 

In [30]:
(a, b) = (4, 3)

(4, 3)

In [44]:
matrix_x = zeros(a, b)

4×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

You should be able to evaluate this piece of code if you go through it slowly. You have been provided all the tools to do this. 

In [45]:
for i in 1:a, j = 1:b
    matrix_x[i, j] = 10 * i + j
end

In [41]:
matrix_x

4×3 Matrix{Int64}:
 11  12  13
 21  22  23
 31  32  33
 41  42  43

### Iterables

In [ ]:
actions = ["watch Netflix", "like 318 homework"]

In [ ]:
for action in actions
    println("Peter doesn't $action")
end

In [ ]:
for i in 1:3
    println(i)
end

In [ ]:
x_values = 1:5

In [ ]:
for x in x_values
    println(x * x)
end

In [ ]:
for i in eachindex(x_values)
    println(x_values[i] * x_values[i])
end

In [ ]:
countries = ("Japan", "Korea", "China")

In [ ]:
cities = ("Tokyo", "Seoul", "Beijing")

In [ ]:
for (country, city) in zip(countries, cities)
    println("The capital of $country is $city")
end

In [ ]:
for (i, country) in enumerate(countries)    
    println(i, " ", country)

    #city = cities[i]
    #println("The capital of $country is $city")

end

### Comprehensions

In [ ]:
doubles = [ 2i for i in 1:4 ]

In [ ]:
[ i + j for i in 1:3, j in 4:6 ]

### Breaks

In [ ]:
y_array = []
x_array = collect(0:9)

In [ ]:
for (i, x) in enumerate(x_array)
    
    if i == 1
        continue
    elseif i == 4
        break
    end
    
    append!(y_array, x^2)
end

println(y_array)

## Functions

Functions are key to writing more complex code. You should always write in terms of functions if possible. From mathematics we know that a function is an abstraction that takes in some input and returns an output. In the world of computing the idea is similar. Let us take a look at some functions below.

The most common way to write a function is the following.

In [ ]:
function f(x) # function header
    return x ^ 2 # body of the function
end

This function accepts one input and returns one output. Namely, it takes the value of `x` and then squares it. 

In [ ]:
f(2)

A shorter way to write the same function is, 

In [ ]:
g(x) = x ^ 2

In [ ]:
g(2)

We could also use an anonymous function, as follows. 

In [ ]:
h = (x) -> x ^ 2 # Lambda or anonymous function

In [ ]:
h(2)

With the following function we have two inputs, `x` and `y`, that return one output. 

In [ ]:
function k(x, y)
    """ This is a function that squares things 
    
    k(x, y; a) 

    a is this keyword argument
    """
    return x ^ 2 + y ^ 2
end

In [ ]:
k(2, 2)

In [ ]:
function m(x, y)
    z = x ^ 2
    q = y ^ 2
    
    return z, q
end

In [ ]:
z, q = m(2, 2)

In [ ]:
z

In [ ]:
q

### Type annotations for functions (optional)

I just want to squeeze in a quick word about types here before we continue. This is an optional section and has more to do with the Julia type system. It is a bit more technical, so you can skip on the first reading. 

Within the Julia type system, we can restrict our function to only accept a certain type of input. We covered the different primitive types such as integers and floats. In order to do this all that you need to do is add `::TypeName` after the input argument for the function. Let us showcase this with an example. 

In [ ]:
fun_1(x::Int64) = x + 2
fun_1(x::Float64) = x * 2 

What you see above is that this function, `fun_1`, is a generic function with two **methods**. In the case above, the output that you receive depends on the **type** of input that you provide. This is an example of *multiple dispatch*. This is one of the unique selling points of Julia, that not many other languages have. 

Let us show how the return value differs based on different inputs. 

In [ ]:
fun_1(1)

In [ ]:
fun_1(1.0)

### What is `return`? (optional)

We mentioned the return value in the previous section so let us talk about the `return` part of the function body. What does it actually represent? 

`return` basically instructs the program to exit the function and return the specified value. 

Let us look at an example of where the `return` part will prevent execution of other parts of the function. 

In [ ]:
function return_example_1(x)

    if x > 5
        return x + 5 # this will exit the function immediately

        println(x - 9) # this will never execute, it is after the return
    end

    return x / 5 # if x <= then this will be returned
end


In [ ]:
return_example_1(1)

In [ ]:
return_example_1(10) # notice that the `println(x - 9)` doesn't execute

You don't have to write `return` in the body of the function. In Julia the function will return the last line of the function. However, it is good coding practice to write `return` so that you can see within the function what is being returned. 

In [ ]:
function return_example_2a(x)
    y = x / 2 # this is the part that will be returned
end

In [ ]:
return_example_2a(4)

In [ ]:
function return_example_2b(x)
    y = x % 2 
    x # this is now the part that will be returned
end

In [ ]:
return_example_2b(4)

You can also get multiple values returned, 

In [ ]:
function return_example_2c(x)
    y = x % 2 
    y + x, y - x, y * x, y / x # this will generate multiple return values
end

In [ ]:
return_example_2c(4)

You will notice that the return above has parentheses around it, which means that the values are contained in a tuple. Remember our discussion on tuples (an immutable type) from earlier.  

### Scope

In [ ]:
a = 2 # global variable

In [ ]:
function f(x)
    return x ^ a
end

In [ ]:
function g(x; a = 2)
    return x ^ a
end

In [ ]:
function h(x)
    a = 2 # a is local 
    return x ^ a
end

In [ ]:
f(2), g(2), h(2)

In [ ]:
a += 1

In [ ]:
f(2), g(2), h(2)

Never rely on global variables! 

### Keyword arguments

In [ ]:
function p(x, y; a = 2, b = 2)
    return x ^ a + y ^ b
end

In [ ]:
p(2, 4)

In [ ]:
p(2, 4, b = 4)

In [ ]:
p(2, 4, a = 4)

## Floating point numbers

Quick introduction to the idea of floating point numbers

In [ ]:
x = 0.1

In [ ]:
10 * x

Simple sums don't always give the answers that you would expect.

In [ ]:
x + x + x + x + x + x + x + x + x + x

Another surprising result

In [ ]:
0.1 == 0.10000000000000001

Comparison of floating point numbers is therefore problematic

In [ ]:
a = 0.001
b = 11.11
c = 1000
test = (a*c)/(b*c) == a/b